CREATE TABLE CONVERSION (
    ID INT NOT NULL AUTO_INCREMENT,
    SRC_CURRENCY VARCHAR(255),
    TGT_CURRENCY VARCHAR(255),
    EXG_RATE VARCHAR(255),
    CONVERSION_DATE DATE,
    PRIMARY KEY (ID)
);